/* soapServerLib.cpp
   Generated by gSOAP 2.8.70 for ISoap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** Use this file in your project build instead of the two files soapC.cpp and soapServer.cpp. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#define SOAP_FMAC3 static
#include "soapC.cpp"
#include "soapServer.cpp"

/* End of soapServerLib.cpp */
