/* soapClient.cpp
   Generated by gSOAP 2.8.70 for ISoap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.70 2019-07-24 10:12:19 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_dataStream(struct soap *soap, const char *soap_endpoint, const char *soap_action, const std::string& szSendMsg, std::string &szRetMsg)
{	struct dataStream soap_tmp_dataStream;
	struct dataStreamResponse *soap_tmp_dataStreamResponse;
	soap_tmp_dataStream.szSendMsg = szSendMsg;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_dataStream(soap, &soap_tmp_dataStream);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_dataStream(soap, &soap_tmp_dataStream, "dataStream", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_dataStream(soap, &soap_tmp_dataStream, "dataStream", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<std::string*>(&szRetMsg)) // NULL ref?
		return soap_closesock(soap);
	soap_default_std__string(soap, &szRetMsg);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_dataStreamResponse = soap_get_dataStreamResponse(soap, NULL, "dataStreamResponse", NULL);
	if (!soap_tmp_dataStreamResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	szRetMsg = soap_tmp_dataStreamResponse->szRetMsg;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
