#ifndef GRADIENTEDITOR_GLOBAL_H
#define GRADIENTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRADIENTEDITOR_LIBRARY)
#  define GRADIENTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRADIENTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRADIENTEDITOR_GLOBAL_H
